pull_request_rules:
  - name: Automatic merge for udpraft modules
    conditions:
      - "status-success=ci/circleci: validate"
      - base=master
      - label="🚀 MERGE ME!"
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart+fasttrack
        strict_method: rebase

