version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd ./modules/typescript/aws-lambdas-multi-handler
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
